.build: &build
  stage: build
  image: $IMAGE:$DIST
  script:
   - (test -n "$APT_URL" && sed -i "s#archive.ubuntu.com#${APT_URL}#" /etc/apt/sources.list ) || true
   - apt-get update && apt-get install -y --no-install-recommends ca-certificates build-essential cmake libboost-dev libboost-filesystem-dev libboost-system-dev libboost-serialization-dev libboost-thread-dev libboost-graph-dev libboost-regex-dev fakeroot debhelper dpkg-dev devscripts libeigen3-dev wget 
   - mkdir deps && cd deps 
   - export BASE=https://download.roboticsapi.org/upload && \
   - wget "${BASE}/liborocos-kdl-dev_${KDLVERSION}-${DIST}_${ARCH}.deb" && \
   - wget "${BASE}/liborocos-kdl_${KDLVERSION}-${DIST}_${ARCH}.deb" && \
   - wget "${BASE}/liborocos-rtt-common2.6-dev_${RTTVERSION}-${DIST}_${ARCH}.deb" && \
   - wget "${BASE}/liborocos-rtt-gnulinux2.6-dev_${RTTVERSION}-${DIST}_${ARCH}.deb" && \
   - wget "${BASE}/liborocos-rtt-gnulinux2.6_${RTTVERSION}-${DIST}_${ARCH}.deb" && \
   - wget "${BASE}/orocos-rtt-dbg2.6_${RTTVERSION}-${DIST}_${ARCH}.deb" && \
   - dpkg -i *.deb && cd .. && rm -rf deps && \
   - mkdir $DIST-$ARCH && cd $DIST-$ARCH && cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=$PROCESSOR .. && make -j 4 && cpack -G DEB && cd ..

.i386: &i386
  ARCH: i386
  PROCESSOR: i686
  IMAGE: i386/ubuntu

.amd64: &amd64
  ARCH: amd64
  PROCESSOR: x86_64
  IMAGE: ubuntu

.ubuntu1604: &ubuntu1604
  DIST: "16.04"

.ubuntu1804: &ubuntu1804
  DIST: "18.04"

.orocos: &orocosversion
  KDLVERSION: 1.0.0-roboticsapi
  RTTVERSION: 2.6.0-99-roboticsapi


16.04-amd64:
  variables:
   <<: *amd64
   <<: *ubuntu1604
   <<: *orocosversion
  <<: *build

16.04-i386:
  variables:
   <<: *i386
   <<: *ubuntu1604
   <<: *orocosversion
  <<: *build
